import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { api } from '../utils/api'
import { formatCoinPrice, formatPercent, formatMarketCap, formatSupply, formatDate } from '../utils/format'

const CHAIN_COLORS = {
  ethereum: 'bg-blue-500/20 text-blue-400',
  bsc: 'bg-yellow-500/20 text-yellow-400',
  solana: 'bg-purple-500/20 text-purple-400',
  polygon: 'bg-violet-500/20 text-violet-400',
  arbitrum: 'bg-sky-500/20 text-sky-400',
  base: 'bg-blue-500/20 text-blue-300',
}

const RISK_COLORS = {
  Low: 'text-accent-green',
  Medium: 'text-accent-yellow',
  High: 'text-orange-400',
  'Very High': 'text-accent-red',
}

export default function CoinReport() {
  const { address } = useParams()
  const navigate = useNavigate()
  const { t } = useTranslation('coins')
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    if (!address) return
    setLoading(true)
    setError(null)
    api.getCoinReport(address).then(data => {
      if (data.error) setError(data.error)
      else setReport(data)
      setLoading(false)
    }).catch(e => {
      setError(e.message)
      setLoading(false)
    })
  }, [address])

  const handleShare = () => {
    if (!report) return
    const text = [
      `${report.basic?.name} (${report.basic?.symbol})`,
      `Chain: ${report.chain}`,
      `Price: ${formatCoinPrice(report.market?.price_usd)}`,
      `Market Cap: ${formatMarketCap(report.market?.market_cap)}`,
      `24h: ${formatPercent(report.market?.change_24h)}`,
      `7d: ${formatPercent(report.market?.change_7d)}`,
      report.risk ? `Risk: ${report.risk.risk_level} (${report.risk.tier})` : '',
      `\nAddress: ${address}`,
      `Generated by BTC Seer`,
    ].filter(Boolean).join('\n')
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  if (loading) {
    return (
      <div className="px-4 pt-4 space-y-4 pb-20">
        <div className="h-6 w-20 bg-bg-card rounded animate-pulse" />
        <div className="h-12 bg-bg-card rounded-xl animate-pulse" />
        <div className="h-32 bg-bg-card rounded-xl animate-pulse" />
        <div className="grid grid-cols-2 gap-3">
          {[1, 2, 3, 4].map(i => <div key={i} className="h-16 bg-bg-card rounded-xl animate-pulse" />)}
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="px-4 pt-4 pb-20">
        <button onClick={() => navigate('/coins')} className="text-accent-blue text-sm mb-4">&larr; {t('title')}</button>
        <div className="bg-bg-card rounded-xl p-6 border border-accent-red/20 text-center">
          <p className="text-accent-red text-sm mb-3">{error}</p>
          <button
            onClick={() => { setLoading(true); setError(null); api.getCoinReport(address).then(d => { if (d.error) setError(d.error); else setReport(d); setLoading(false) }).catch(e => { setError(e.message); setLoading(false) }) }}
            className="text-accent-blue text-xs underline"
          >
            {t('app.retry', { ns: 'common' })}
          </button>
        </div>
      </div>
    )
  }

  if (!report) return null

  const chainClass = CHAIN_COLORS[report.chain] || 'bg-white/10 text-text-muted'
  const riskClass = report.risk ? RISK_COLORS[report.risk.risk_level] || '' : ''

  return (
    <div className="px-4 pt-4 space-y-4 pb-20">
      <button onClick={() => navigate(-1)} className="text-accent-blue text-sm">&larr; {t('nav.back', { ns: 'common' })}</button>

      {/* Header */}
      <div className="flex items-center gap-3">
        {report.basic?.image ? (
          <img src={report.basic.image} alt="" className="w-10 h-10 rounded-full" />
        ) : (
          <div className="w-10 h-10 rounded-full bg-accent-blue/20 flex items-center justify-center font-bold text-accent-blue">
            {report.basic?.symbol?.[0] || '?'}
          </div>
        )}
        <div className="flex-1">
          <h1 className="text-lg font-bold">{report.basic?.name || t('report.unknownToken')}</h1>
          <div className="flex items-center gap-2">
            <span className="text-xs text-text-muted">{report.basic?.symbol}</span>
            <span className={`text-[10px] px-2 py-0.5 rounded-full capitalize ${chainClass}`}>{report.chain}</span>
          </div>
        </div>
      </div>

      {/* Market Overview */}
      <div className="bg-bg-card rounded-xl p-4 border border-white/5">
        <h3 className="text-xs font-semibold text-text-muted mb-3">{t('report.overview')}</h3>
        <div className="space-y-3">
          <div className="flex justify-between items-baseline">
            <span className="text-text-muted text-xs">{t('detail.price')}</span>
            <span className="text-lg font-bold">{formatCoinPrice(report.market?.price_usd)}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-text-muted text-xs">{t('detail.marketCap')}</span>
            <span className="text-sm font-semibold">{formatMarketCap(report.market?.market_cap)}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-text-muted text-xs">{t('detail.volume24h')}</span>
            <span className="text-sm font-semibold">{formatMarketCap(report.market?.volume_24h)}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-text-muted text-xs">{t('detail.change24h')}</span>
            <span className={`text-sm font-semibold ${(report.market?.change_24h || 0) >= 0 ? 'text-accent-green' : 'text-accent-red'}`}>
              {formatPercent(report.market?.change_24h)}
            </span>
          </div>
          <div className="flex justify-between">
            <span className="text-text-muted text-xs">7d</span>
            <span className={`text-sm font-semibold ${(report.market?.change_7d || 0) >= 0 ? 'text-accent-green' : 'text-accent-red'}`}>
              {formatPercent(report.market?.change_7d)}
            </span>
          </div>
        </div>
      </div>

      {/* Detail Stats */}
      {report.detail && (
        <div className="grid grid-cols-2 gap-3">
          {report.detail.market_cap_rank && (
            <div className="bg-bg-card rounded-xl p-3 border border-white/5">
              <p className="text-[10px] text-text-muted mb-1">{t('report.rank')}</p>
              <p className="text-sm font-bold">#{report.detail.market_cap_rank}</p>
            </div>
          )}
          {report.detail.ath && (
            <div className="bg-bg-card rounded-xl p-3 border border-white/5">
              <p className="text-[10px] text-text-muted mb-1">{t('report.ath')}</p>
              <p className="text-sm font-bold">{formatCoinPrice(report.detail.ath)}</p>
              {report.detail.ath_date && <p className="text-[10px] text-text-muted">{formatDate(report.detail.ath_date)}</p>}
            </div>
          )}
          {report.detail.atl && (
            <div className="bg-bg-card rounded-xl p-3 border border-white/5">
              <p className="text-[10px] text-text-muted mb-1">{t('report.atl')}</p>
              <p className="text-sm font-bold">{formatCoinPrice(report.detail.atl)}</p>
              {report.detail.atl_date && <p className="text-[10px] text-text-muted">{formatDate(report.detail.atl_date)}</p>}
            </div>
          )}
          {report.detail.circulating_supply && (
            <div className="bg-bg-card rounded-xl p-3 border border-white/5">
              <p className="text-[10px] text-text-muted mb-1">{t('report.circulating')}</p>
              <p className="text-sm font-bold">{formatSupply(report.detail.circulating_supply, report.basic?.symbol)}</p>
            </div>
          )}
          {report.detail.total_supply && (
            <div className="bg-bg-card rounded-xl p-3 border border-white/5">
              <p className="text-[10px] text-text-muted mb-1">{t('report.totalSupply')}</p>
              <p className="text-sm font-bold">{formatSupply(report.detail.total_supply, report.basic?.symbol)}</p>
            </div>
          )}
          {report.detail.fully_diluted_valuation && (
            <div className="bg-bg-card rounded-xl p-3 border border-white/5">
              <p className="text-[10px] text-text-muted mb-1">{t('report.fdv')}</p>
              <p className="text-sm font-bold">{formatMarketCap(report.detail.fully_diluted_valuation)}</p>
            </div>
          )}
        </div>
      )}

      {/* Risk Assessment */}
      {report.risk && (
        <div className="bg-bg-card rounded-xl p-4 border border-white/5">
          <h3 className="text-xs font-semibold text-text-muted mb-3">{t('report.riskAssessment')}</h3>
          <div className="space-y-2">
            <div className="flex justify-between">
              <span className="text-text-muted text-xs">{t('report.tier')}</span>
              <span className="text-sm font-semibold">{report.risk.tier}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-text-muted text-xs">{t('report.riskLevel')}</span>
              <span className={`text-sm font-bold ${riskClass}`}>{report.risk.risk_level}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-text-muted text-xs">{t('report.volMcapRatio')}</span>
              <span className="text-sm font-semibold">{(report.risk.volume_mcap_ratio * 100).toFixed(2)}%</span>
            </div>
          </div>
        </div>
      )}

      {/* Categories */}
      {report.categories && report.categories.length > 0 && (
        <div className="bg-bg-card rounded-xl p-4 border border-white/5">
          <h3 className="text-xs font-semibold text-text-muted mb-2">{t('report.categories')}</h3>
          <div className="flex flex-wrap gap-1.5">
            {report.categories.filter(Boolean).slice(0, 8).map(cat => (
              <span key={cat} className="text-[10px] bg-white/5 text-text-secondary px-2 py-0.5 rounded-full">{cat}</span>
            ))}
          </div>
        </div>
      )}

      {/* Description */}
      {report.description && (
        <div className="bg-bg-card rounded-xl p-4 border border-white/5">
          <h3 className="text-xs font-semibold text-text-muted mb-2">{t('report.about')}</h3>
          <p className="text-xs text-text-secondary leading-relaxed">{report.description.replace(/<[^>]*>/g, '')}</p>
        </div>
      )}

      {/* Contract Address */}
      <div className="bg-bg-card rounded-xl p-4 border border-white/5">
        <h3 className="text-xs font-semibold text-text-muted mb-2">{t('report.contract')}</h3>
        <p className="text-[10px] text-text-secondary break-all font-mono">{address}</p>
      </div>

      {/* Share Button */}
      <button
        onClick={handleShare}
        className="w-full bg-accent-blue/10 border border-accent-blue/30 text-accent-blue rounded-xl py-3 text-sm font-medium hover:bg-accent-blue/20 transition-colors"
      >
        {copied ? t('report.copied') : t('report.shareReport')}
      </button>

      <p className="text-text-muted text-[10px] text-center">
        {t('report.reportGenerated', { time: report.generated_at ? new Date(report.generated_at).toLocaleString() : t('time.justNow', { ns: 'common' }) })}
      </p>
    </div>
  )
}
