const tutorialSteps = [
  {
    id: 'welcome',
    title: 'Welcome to Paper Trading',
    description: 'Practice Bitcoin trading with virtual funds. No real money at risk. Follow this guide to learn the Binance-style interface.',
    target: '[data-tutorial="header"]',
    position: 'bottom',
  },
  {
    id: 'position-mode',
    title: 'Position Mode',
    description: 'One-Way mode: only one direction at a time.\nHedge mode: hold LONG and SHORT simultaneously.',
    target: '[data-tutorial="position-mode"]',
    position: 'bottom',
    example: 'Most beginners start with One-Way mode.',
  },
  {
    id: 'margin-mode',
    title: 'Margin Mode',
    description: 'Cross: shares margin across all positions (lower liquidation risk).\nIsolated: margin is locked per trade (limits max loss).',
    target: '[data-tutorial="margin-mode"]',
    position: 'bottom',
    example: 'Isolated is recommended for risk management.',
  },
  {
    id: 'direction',
    title: 'Trade Direction',
    description: 'LONG: profit when price goes UP.\nSHORT: profit when price goes DOWN.\nChoose based on your market analysis.',
    target: '[data-tutorial="direction"]',
    position: 'bottom',
  },
  {
    id: 'order-type',
    title: 'Order Type',
    description: 'Market: execute immediately at current price.\nLimit: set your desired entry price and wait for it to fill.',
    target: '[data-tutorial="order-type"]',
    position: 'bottom',
    example: 'Market orders are simpler. Limit orders can get better prices.',
  },
  {
    id: 'entry-price',
    title: 'Entry Price',
    description: 'For Market orders, this shows the current BTC price.\nFor Limit orders, type your target entry price.',
    target: '[data-tutorial="entry-price"]',
    position: 'bottom',
  },
  {
    id: 'leverage',
    title: 'Leverage',
    description: 'Multiplies your position size AND risk.\n10x leverage = 10x gains OR 10x losses.\nHigher leverage = closer liquidation price.',
    target: '[data-tutorial="leverage"]',
    position: 'bottom',
    example: '2-5x is conservative. 10-20x is moderate. 50x+ is very risky.',
  },
  {
    id: 'size',
    title: 'Position Size',
    description: 'How much USDT to use as margin.\nNotional value = Size x Leverage.\nUse the % buttons for quick sizing.',
    target: '[data-tutorial="size"]',
    position: 'top',
    example: '$10 at 10x = $100 notional exposure.',
  },
  {
    id: 'stop-loss',
    title: 'Stop Loss',
    description: 'Auto-closes your trade if price hits this level.\nLimits your maximum loss on the trade.\nAlways set a stop loss!',
    target: '[data-tutorial="stop-loss"]',
    position: 'top',
  },
  {
    id: 'tp1',
    title: 'Take Profit 1 (40%)',
    description: 'First profit target. Closes 40% of your position.\nLock in gains early while letting the rest run.',
    target: '[data-tutorial="tp1"]',
    position: 'top',
    example: 'Set TP1 at a realistic near-term target.',
  },
  {
    id: 'tp2',
    title: 'Take Profit 2 (40%)',
    description: 'Second target. Closes another 40% of position.\nBy now you\'ve secured 80% of profits.',
    target: '[data-tutorial="tp2"]',
    position: 'top',
  },
  {
    id: 'tp3',
    title: 'Take Profit 3 (20%)',
    description: 'Final target. Closes remaining 20%.\nThis is your "moon bag" - the ambitious target.',
    target: '[data-tutorial="tp3"]',
    position: 'top',
  },
  {
    id: 'preview',
    title: 'Order Preview',
    description: 'Review your full trade setup before submitting.\nShows liquidation price, max loss, max gain, and risk-reward ratio.',
    target: '[data-tutorial="preview"]',
    position: 'top',
  },
  {
    id: 'submit',
    title: 'Open Position',
    description: 'Click to submit your paper trade.\nThe button color matches your direction: green for LONG, red for SHORT.',
    target: '[data-tutorial="submit"]',
    position: 'top',
  },
  {
    id: 'positions',
    title: 'Active Positions',
    description: 'Monitor your open trades here.\nSee real-time P&L, TP progress, and duration.\nClose any trade manually with the Close button.',
    target: '[data-tutorial="positions"]',
    position: 'top',
  },
  {
    id: 'close-trade',
    title: 'Closing a Position',
    description: 'Click "Close" on any active trade to exit.\nYou\'ll see a confirmation before closing.\nP&L is calculated at the current market price.',
    target: '[data-tutorial="positions"]',
    position: 'top',
  },
  {
    id: 'history',
    title: 'Trade History',
    description: 'All closed trades appear here.\nTrack your wins, losses, and close reasons.\nLearn from past trades to improve.',
    target: '[data-tutorial="history-tab"]',
    position: 'bottom',
  },
  {
    id: 'portfolio',
    title: 'Portfolio Summary',
    description: 'Your overall performance at a glance.\nBalance, total P&L, win rate, and progress toward your goal.',
    target: '[data-tutorial="portfolio"]',
    position: 'top',
  },
  {
    id: 'risk-management',
    title: 'Risk Management Tips',
    description: 'Never risk more than 1-2% of balance per trade.\nUse stop losses on every trade.\nDon\'t revenge trade after losses.\nTake breaks between trades.',
    target: '[data-tutorial="header"]',
    position: 'bottom',
  },
  {
    id: 'finish',
    title: 'You\'re Ready!',
    description: 'You now know the basics of paper trading.\nPractice here risk-free before using real funds.\nGood luck on your journey from $10 to $10,000!',
    target: '[data-tutorial="header"]',
    position: 'bottom',
  },
]

export default tutorialSteps
