const tutorialSteps = [
  {
    id: 'welcome',
    title: 'Welcome to Paper Trading',
    description: 'Trade Bitcoin with $10,000 virtual funds using real market data. Your positions react to live BTC price — including auto-liquidation, stop losses, and take profits — just like a real exchange.',
    target: '[data-tutorial="header"]',
    position: 'bottom',
    example: 'This is a safe sandbox. Learn from mistakes here, not with real money.',
  },
  {
    id: 'position-mode',
    title: 'Position Mode',
    description: 'One-Way: you can only hold one direction (LONG or SHORT) at a time. Opening the opposite closes your current position.\nHedge: hold LONG and SHORT simultaneously to hedge risk.',
    target: '[data-tutorial="position-mode"]',
    position: 'bottom',
    example: 'Start with One-Way. Hedge mode is for advanced strategies.',
  },
  {
    id: 'margin-mode',
    title: 'Margin Mode',
    description: 'Cross: your entire balance backs every position. Lower liquidation risk, but one bad trade can drain everything.\nIsolated: only the margin you assign is at risk. Max loss = your margin for that trade.',
    target: '[data-tutorial="margin-mode"]',
    position: 'bottom',
    example: 'Isolated is safer — you can never lose more than your position size.',
  },
  {
    id: 'direction',
    title: 'LONG or SHORT',
    description: 'LONG: you profit when BTC price goes UP. You\'re betting the price will rise.\nSHORT: you profit when BTC price goes DOWN. You\'re betting on a drop.\nThe wrong direction + high leverage = fast liquidation.',
    target: '[data-tutorial="direction"]',
    position: 'bottom',
    example: 'Not sure? Check the AI Advisor tab for signal direction before choosing.',
  },
  {
    id: 'order-type',
    title: 'Market vs Limit Order',
    description: 'Market: fills instantly at the current BTC price. Simple and guaranteed.\nLimit: you set a specific entry price. The trade only opens if BTC reaches that price.',
    target: '[data-tutorial="order-type"]',
    position: 'bottom',
    example: 'Use Market to practice quickly. Use Limit to get better entries on pullbacks.',
  },
  {
    id: 'entry-price',
    title: 'Entry Price',
    description: 'This is the price you enter the trade at.\nMarket order: auto-filled with the live BTC price (read-only).\nLimit order: type your desired entry — it must be below current price for LONG, above for SHORT.',
    target: '[data-tutorial="entry-price"]',
    position: 'bottom',
  },
  {
    id: 'leverage',
    title: 'Leverage — The Risk Multiplier',
    description: 'Leverage multiplies BOTH your profits AND losses.\nAt 10x: a 1% BTC move = 10% gain or loss on your margin.\nAt 100x: a 1% move = 100% — you get liquidated instantly.\nHigher leverage = liquidation price closer to entry.',
    target: '[data-tutorial="leverage"]',
    position: 'bottom',
    example: 'Beginners: stay at 2-5x. Even pro traders rarely go above 20x.',
  },
  {
    id: 'size',
    title: 'Position Size (Margin)',
    description: 'How much USDT you put up as collateral.\nNotional value = Size x Leverage. This is your actual market exposure.\nThe % buttons let you quickly allocate a fraction of your balance.',
    target: '[data-tutorial="size"]',
    position: 'top',
    example: '$10 at 10x = $100 exposure. If BTC moves 10%, you gain or lose $10 (100% of margin).',
  },
  {
    id: 'stop-loss',
    title: 'Stop Loss — Your Safety Net',
    description: 'The price where your position auto-closes to limit losses.\nWhen BTC hits your SL, the system automatically closes your trade — no action needed.\nWithout a SL, your only exit is liquidation or manual close.',
    target: '[data-tutorial="stop-loss"]',
    position: 'top',
    example: 'Rule of thumb: set SL where your trade thesis is invalidated, usually 1-2% from entry.',
  },
  {
    id: 'tp1',
    title: 'Take Profit 1 — Lock In Early Gains',
    description: 'Your first profit target. On real exchanges, this would close 40% of your position.\nTP1 should be a realistic, near-term target based on support/resistance levels.\nThe R:R ratio shown tells you the reward relative to your risk.',
    target: '[data-tutorial="tp1"]',
    position: 'top',
    example: 'If your SL is 2% away, a good TP1 is at least 2% profit (1:1 R:R).',
  },
  {
    id: 'tp2',
    title: 'Take Profit 2 — Secure Most Profits',
    description: 'Second target closes another 40% of your position.\nBy TP2, you\'ve locked in 80% of your profits — the remaining 20% rides for free.\nSet this at a medium-term resistance/support level.',
    target: '[data-tutorial="tp2"]',
    position: 'top',
  },
  {
    id: 'tp3',
    title: 'Take Profit 3 — The Moon Target',
    description: 'Your final target. When BTC hits TP3, the system auto-closes your entire position at full profit.\nThis is your ambitious "moon bag" target.\nThe position auto-closes here — you don\'t need to watch it.',
    target: '[data-tutorial="tp3"]',
    position: 'top',
    example: 'Aim for 3:1 R:R or higher on TP3. Let winners run!',
  },
  {
    id: 'preview',
    title: 'Order Preview — Check Before You Trade',
    description: 'Review everything before submitting:\n- Liquidation Price: where you lose 100% of margin\n- Max Loss: your worst case (at SL)\n- Max Gain: your best case (at TP3)\n- R:R Ratio: reward divided by risk (aim for 2+ )',
    target: '[data-tutorial="preview"]',
    position: 'top',
    example: 'If R:R is below 1.5, your risk is too high relative to reward. Adjust your levels.',
  },
  {
    id: 'submit',
    title: 'Open Your Position',
    description: 'Hit this button to open your paper trade with live BTC data.\nGreen = LONG (you\'re bullish).\nRed = SHORT (you\'re bearish).\nOnce open, the system monitors your trade 24/7.',
    target: '[data-tutorial="submit"]',
    position: 'top',
  },
  {
    id: 'positions',
    title: 'Active Positions — Live Monitoring',
    description: 'Your open trades update with the live BTC price.\nWatch your unrealized P&L, TP progress bar, and liquidation distance.\nThe system auto-closes trades when SL, TP3, or liquidation price is hit — just like Binance.',
    target: '[data-tutorial="positions"]',
    position: 'top',
    example: 'Trades are checked every 5 minutes. You can also close manually anytime.',
  },
  {
    id: 'liquidation',
    title: 'Liquidation — The Biggest Risk',
    description: 'If BTC moves far enough against you, your position gets liquidated.\nLiquidation = you lose 100% of your margin on that trade.\nHigher leverage = liquidation price closer to entry.\nAt 100x LONG, just a ~1% drop liquidates you.',
    target: '[data-tutorial="preview"]',
    position: 'top',
    example: '10x LONG at $100k → liquidated at ~$90k.\n100x LONG at $100k → liquidated at ~$99k.',
  },
  {
    id: 'history',
    title: 'Trade History — Learn From Every Trade',
    description: 'Every closed trade is recorded with:\n- Win/Loss result and exact P&L\n- Close reason (manual, stop_loss, take_profit, liquidated)\n- Entry to exit price and trade duration\nReview your history to spot patterns in your wins and losses.',
    target: '[data-tutorial="history-tab"]',
    position: 'bottom',
  },
  {
    id: 'portfolio',
    title: 'Portfolio — Track Your Journey',
    description: 'Your overall stats: balance, total P&L, and win rate.\nThe progress bar tracks your journey from $10 to $10,000.\nAim for consistent small wins rather than big risky bets.',
    target: '[data-tutorial="portfolio"]',
    position: 'top',
    example: 'A 60% win rate with 2:1 R:R is highly profitable long-term.',
  },
  {
    id: 'risk-management',
    title: 'Golden Rules of Trading',
    description: 'Never risk more than 1-2% of balance per trade.\nAlways use a stop loss — no exceptions.\nDon\'t increase leverage after a loss (revenge trading).\nTake breaks after 3 consecutive losses.\nThe goal is survival first, profits second.',
    target: '[data-tutorial="header"]',
    position: 'bottom',
    example: 'Most traders blow up from over-leveraging, not from bad direction calls.',
  },
  {
    id: 'finish',
    title: 'You\'re Ready to Trade!',
    description: 'Everything here uses real BTC price data with realistic mechanics:\n- Auto-liquidation at your liquidation price\n- Auto-close at stop loss and take profit\n- Real-time P&L tracking\n\nStart small, learn the patterns, and build your edge.\nGood luck on your $10 to $10,000 journey!',
    target: '[data-tutorial="header"]',
    position: 'bottom',
  },
]

export default tutorialSteps
